name: "機能提案"
description: "新しい機能や改善点の提案はこちら"
title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        改善提案ありがとうございます！提案の内容や背景を記載していただけると助かります 🙏

  - type: input
    id: title
    attributes:
      label: "機能タイトル"
      description: "提案する機能・改善のタイトル（簡潔に）"
      placeholder: "例: ボタンにローディング状態を追加する"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: "背景・目的"
      description: "なぜこの機能が必要か、どんな課題があるかを教えてください。"
      placeholder: |
        現在のUIではユーザーがボタンを押した後の処理中かどうか分かりません。
        明示的なフィードバックを提供するためにローディング表示が必要です。
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "提案内容"
      description: "実装方法のアイデアや想定している仕様について記述してください。"
      placeholder: |
        - `<Button>` に `isLoading` props を追加
        - 処理中はスピナーアイコンとともにボタンが無効化される
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "代替案・他の選択肢"
      description: "他に検討した方法があれば教えてください（任意）"
      placeholder: "例: トースト通知で完了を知らせる方法もあるが、即時性に欠ける"

  - type: textarea
    id: additional
    attributes:
      label: "その他の情報"
      description: "スクリーンショット、参考リンク、関連Issueなどあれば記載してください。"
