name: Release on tag

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Enable and install pnpm via corepack
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v  # ← 念のためバージョン確認（ログ出力用）

            - name: Install dependencies
              run: pnpm install

            - name: Version packages
              run: pnpm changeset version

            - name: Re-install to update lockfile
              run: pnpm install

            - name: Publish packages
              run: pnpm changeset publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
