name: Release

on:
    push:
        tags:
            - "v*" # タグが付けられたときのみトリガー

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js (latest)
              uses: actions/setup-node@v3
              with:
                  node-version: "latest" # 最新のNode.jsバージョンを使用

            - name: Install pnpm
              run: npm install -g pnpm # pnpm をインストール

            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            - name: Generate changeset
              run: pnpm changeset

            - name: Version packages
              run: pnpm changeset version

            - name: Publish packages
              run: pnpm publish --access public --no-git-checks --filter "@kids-game-ui/*"

            - name: Push changes
              run: git push origin HEAD

            - name: Create GitHub release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }} # タグ名をそのまま使用
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes made in this release:
                      ${{ steps.changeset.outputs.changeset_list }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
