name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Node.js (latest)
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            - name: Apply version updates from changesets
              run: pnpm changeset version

            - name: Commit version bumps and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "chore(release): apply version bumps"
                  git push origin HEAD:main --follow-tags

            - name: Build packages
              run: pnpm run build

            - name: Publish packages
              run: pnpm changeset publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node for changelog script
              run: pnpm add -D @changesets/get-release-plan

            - name: Generate release notes
              run: node scripts/get-changelog.mjs

            - name: Create GitHub release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body_path: release-notes.txt
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
