name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # タグや履歴を含めて取得するため重要

            - name: Set up Node.js (latest)
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            - name: Generate changeset
              run: pnpm changeset

            - name: Version packages
              run: pnpm changeset version

            - name: Log in to npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Verify npm authentication
              run: npm whoami
              continue-on-error: false

            - name: Publish packages
              run: pnpm publish --access public --no-git-checks --filter "@kids-game-ui/*"

            - name: Remove changeset files
              run: |
                  git rm .changeset/*.md || true

            - name: Commit removal of changeset files
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git commit -m "chore: remove consumed changesets" || echo "No changes to commit"

            - name: Push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git push origin HEAD:main

            - name: Generate release notes
              run: |
                  # 変更履歴を生成してGitHub Releaseに追加
                  npx changeset release

            - name: Create GitHub release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: ${{ steps.changelog.outputs.changelog }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
